### ISSUE TITLE
New Example

### ISSUE THREAD

**Issue by kanekotic** [jjrdk/ArchiMetrics#11]
First of all great job.

The current example on the ReadMe.md is out of date CodeMetricsCalculator now requires two parameters. I have downloaded the latest version nuget package of ArchMetrics. I am a bit confused on how to use the API.  

My intention is tu pass a SytaxTree or string related to a method and obtain the metrics from it, is this possible?

**Comment by jjrdk** [comment]
I just released v.1 and the CodeMetricsCalculator has a default constructor again.

**Comment by kanekotic** [comment]
thank you very much :+1:  

I will try it in a moment
