### ISSUE TITLE
Not ready for C# 6

### ISSUE THREAD

**Issue by AlbertoMonteiro** [jjrdk/ArchiMetrics#12]
I added a single test in **ArchiMetrics.Analysis.Tests.Metrics.CodeMetricsCalculatorTests** and it failed

````csharp
[Test]
public async Task CanCalculateMetricsForClassSnippet2()
{
	const string Snippet = @"
public class Something {
	public string Name => ""Alberto"";
}
";
	var tree = CSharpSyntaxTree.ParseText(Snippet);
	var task = await _analyzer.Calculate(new[] { tree });

	var metrics = task.AsArray();
	Assert.IsNotEmpty(metrics);
}
````

It fails on **VisitPropertyDeclaration** method in **MemberCollector** class

Have you plans to support C# 6 features?

**Comment by jjrdk** [comment]
Yes.

**Comment by jjrdk** [comment]
I pushed a fix for handling ArrowExpressionSyntax and included your test.
