### ISSUE TITLE
Project calculator visibility is internal

### ISSUE THREAD

**Issue by pjmagee** [jjrdk/ArchiMetrics#14]

**Comment by jjrdk** [comment]
and?

**Comment by pjmagee** [comment]
Nobody can use it...I pulled source and made it public to use it. Just thought you might want to know if you publish a new nuget. As of this moment, people cannot use it unless they pull down. 

I can send a PR if you'd like?

**Comment by jjrdk** [comment]
It was actually intentional to hide it. What is the use case that you need it to be public for?

**Comment by pjmagee** [comment]
So that I can use it instead of having to new up the `CodeMetricsCalculator`. Because this one doesn't give you project level dependencies which you mention this framework can do on the `readme.md` file. I thought `ProjectMetricsCalculator` appears to be a front facing API class, to be used by someone consuming the framework, otherwise it appears to have no use if left as internal?

**Comment by jjrdk** [comment]
Makes sense, I guess somewhere in my head it should have been made public if it was part of the documentation.

If you send me a pull request, then I would ask that you move the `ProjectMetricsCalculator` to the ArchiMetrics.Analysis root namespace so it is discoverable.

**Comment by pjmagee** [comment]
Sounds reasonable!

**Comment by pjmagee** [comment]
I've created a pull request.

**Comment by jjrdk** [comment]
Closed with #16 .

**Comment by jjrdk** [comment]
Included in v.1.1 - https://www.nuget.org/packages/ArchiMetrics.Analysis/1.1.0
