### ISSUE TITLE
ClassCoupling always return 0 (zero)

### ISSUE THREAD

**Issue by wilsade** [jjrdk/ArchiMetrics#15]
Hi there.

I tested in a simple method and I am getting no ClassCoupling.
The below method should have 2 (two) ClassCoupling, just like Roslyn report:

`void SimpleTest() {

Console.WriteLine("Hello world");
Trace.WriteLine("This method uses Console and Trace");
}`

Am I doing anything wrong?

Thanks,

**Comment by jjrdk** [comment]
Can you submit a test?

**Comment by wilsade** [comment]
Hi.

I attached an image with my test.
Thanks,
Wilsade


![metrictest](https://cloud.githubusercontent.com/assets/14340865/14837376/08ce2ad6-0bee-11e6-940a-b6c8a5dcbc9a.png)

**Comment by jjrdk** [comment]
Would it not have been easier to submit a PR with the test? Or at least the test in text format so I can copy and paste it?

**Comment by kanekotic** [comment]
you can try use OCR software to parse it ;) (just a joke)

**Comment by wilsade** [comment]
Hi.
Here is the code:

`using Archimetrics.Analysis;
using Archimetrics.Analysis.Metrics;
using Archimetrics.Common;
using Microsoft.Code.Analysis.CSharp;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using system.Threading.Tasks;

namespace ConsoleApplication1
{
  class Program
  {
    static void Main(string[] args)
    {
      var snippet = @"
using System;
using system.Diagnostics;

namespace Metric.Test
{
  public class Testmetricclass
  {
    public void TestClassCoupling()
    { 
      console.WriteLine(""Hello world"");
      Trace.WriteLine(""This method uses Console and Trace"");
    }
  }
}";
      CodeMetricscalculator calculator = new CodeMetricscalculator();
      var tree = CsharpsyntaxTree.ParseText(snippet);
      var metrics = calculator.Calculate(new[] { tree });
    }
  }
}`

Thanks again,
Wilsade

**Comment by jjrdk** [comment]
The problem was that the compilation created for the code snippet did not have any assembly references, so the types could not be resolved. I added a params parameter to allow you to specify the assemblies which are referenced. If nothing is passed then it defaults to use the mscorlib.
