### ISSUE TITLE
Add Class Count

### ISSUE THREAD

**Issue by pjmagee** [jjrdk/ArchiMetrics#17]
Not part of the standard metrics but I think it would be nice to extend Project Metrics / Namespace Metrics to include number of classes, interfaces etc.

**Comment by jjrdk** [comment]
I agree, but since these are very simple to calculate using LINQ then I don't see much value in including them in the project.

Do you have a specific use case? Reporting?

**Comment by pjmagee** [comment]
Hmm, no I dont have a specific use case. I thought IProjectMetric would be a good place as it's a high level overview. I've seen other tools provide this along with "Methods" and "Static Methods". 

I mean, It would just be good to include in ArchiMetrics as it's a really nice wrapper around Roslyn.
