### ISSUE TITLE
Cannot update nuget to 1.1.0

### ISSUE THREAD

**Issue by pjmagee** [jjrdk/ArchiMetrics#19]
It seems to revert due to wanting to install System.Runtime.

**Comment by fntsrlike** [comment]
I can't install ArchiMetrics 1.1.0, either;

Error is:
```
Failed to add reference to 'System.Collections`. Please make sure that it is in the Global Assembly Cache.
```

My Microsoft.CodeAnalysis version is `1.2.2`
