### ISSUE TITLE
Incorrect version in packages.config

### ISSUE THREAD

**Issue by AndreyAkinshin** [jjrdk/ArchiMetrics#20]
There is the following line in ` ArchiMetrics/tests/ArchiMetrics.CodeReview.Rules.Tests/packages.config
`:
```
<package id="DotNetZip.Reduced" version=" " targetFramework="net452" />
```
You probably should specify correct version number for `DotNetZip.Reduced` (space is illegal in this context).

**Comment by jjrdk** [comment]
Feel free to submit a PR.

**Comment by AndreyAkinshin** [comment]
Any troubles with the PR?
