### ISSUE TITLE
Can't build in VS2015 UP3

### ISSUE THREAD

**Issue by markheath** [jjrdk/ArchiMetrics#22]
I've had problems trying to build the solution in VS2015 Update 3 due to some weird issue with NuGet package restore:

```
Error occurred while restoring NuGet packages: Cannot cast Newtonsoft.Json.Linq.JArray to Newtonsoft.Json.Linq.JToken.
```

After many wild guesses, I decided to delete all lines from project.json that contained arrays, (e.g. lists of authors, tags etc) and that seemed to fix the issue. Is this something weird with my setup or has anyone else run into this

**Comment by jjrdk** [comment]
I have moved away from VS2015 and am now using the VS2017 csproj format. (Hopefully it will remain stable).
